name: CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
            - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: yarn db:create --host=localhost --port=5432
        env:
          PGPASSWORD:postgres

      - run: yarn install
      - run: yarn build
      - run: yarn test

      - name: Create Build
        run: |
          yarn workspace bot run build
        env: 
          PACKAGE_NAME: onesup
          HOSTNAME: onesup.azurewebsites.net
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          MICROSOFT_APP_ID: ${{ secrets.MICROSOFT_APP_ID }}
          CONNECTOR_ID: ${{ secrets.CONNECTOR_ID }}
          SUPBOT_APP_ID: ${{ secrets.SUPBOT_APP_ID }}
          SUPBOT_APP_URI: ${{ secrets.SUPBOT_APP_URI }}

