name: CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: yarn install
      - run: gulp build
      - run: gulp manifest
      - run: yarn test
